version: '3.8'

networks:
  webNet:
    driver: bridge
    internal: false
    name: webNet
    enable_ipv6: false

services:

  #NodeJS
  nodeWebServer:
    image: node:16.13.2
    networks:
      - webNet
    hostname: nodeWebServer
    container_name: nodeWebServer
    restart: unless-stopped
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: "npx pm2-runtime start ./webServer/dist/pm2.config.js"